name: HACS Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HACS Action
        uses: hacs/action/validate@main
        with:
          category: integration
